# Generated by Django 5.2.4 on 2026-04-23 13:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={
                 'unique': 'Пользователь с таким email уже существует'}, max_length=254, unique=True, verbose_name='адрес электронной почты')),
                ('name', models.CharField(max_length=124, verbose_name='имя')),
                ('surname', models.CharField(max_length=124, verbose_name='фамилия')),
                ('avatar', models.ImageField(blank=True, null=True,
                 upload_to='avatars/', verbose_name='аватар')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(
                    message='Номер телефона должен быть в формате 8xxxxxxxxxx или +7xxxxxxxxxx', regex='^(\\+7|8)\\d{10}$')], verbose_name='номер телефона')),
                ('github_url', models.URLField(blank=True, null=True, validators=[
                 django.core.validators.URLValidator()], verbose_name='ссылка на GitHub')),
                ('about', models.TextField(blank=True, max_length=256,
                 null=True, verbose_name='описание профиля')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='активный пользователь')),
                ('is_staff', models.BooleanField(
                    default=False, verbose_name='администратор')),
                ('date_joined', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                 related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                 related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-date_joined'],
            },
        ),
    ]
