# Generated by Django 5.2.4 on 2026-04-23 13:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание проекта')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания проекта')),
                ('github_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='ссылка на GitHub')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=6, verbose_name='статус проекта')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
